### ISSUE TITLE
Despliegue

### ISSUE THREAD

**Issue by reyescuesta2** [jorgeMunozCampanillas/Lizard#1]
https://github.com/IESCampanillas/proyectos-daw-2022/wiki/Despliegue-de-Aplicaciones-Web
Necesito que me especifiques mejor los requisitos de despliegue, en concreto:
Desplegar la aplicación en la nube: Necesito que me especifiques en que hosting vas a desplegar la aplicación
Dominio: Necesito que me especifiques que tipo de dominio vas a utilizar (si uno gratuito, uno .es, .com?)
SGBD: Necesito que especifiques donde vas a alojar la base de datos donde mismo que la web o en un servidor aparte?

**Comment by jorgeMunozCampanillas** [comment]
Me acaba de llegar el issues y pone que es de hace 20 dias ya lo especifique, gracias!!
